{% set name = "pdpipe" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 56074ebfd44ea20b95b3fb01f8e4427cac8781679820e9a9d8cb2c58d63396e7

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - versioneer-518
  run:
    - python >={{ python_min }},<3.11
    - pandas >=0.18.0
    - sortedcontainers
    - strct
    - tqdm
    - skutil >=0.0.15
    - birch

test:
  requires:
    - python {{ python_min }}
  imports:
    - pdpipe

about:
  home: https://pdpipe.github.io/pdpipe/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Easy pipelines for pandas.
  doc_url: https://pdpipe.github.io/pdpipe/doc/pdpipe/
  dev_url: https://github.com/pdpipe/pdpipe

  description: |
    Ever written a preprocessing pipeline for pandas dataframes and had trouble serializing it for later depoloyment on a different machine? Ever needed fit-able preprocessing transformations, that have tunable paramaters that are inferred from training data, to be used later to transform input data? Ever struggled with preprocessing different types of data in the same pandas dataframe? Enter pdpipe, a simple framework for serializable, chainable and verbose pandas pipelines. Its intuitive API enables you to generate, using only a few lines, complex pandas processing pipelines that can easily be broken down or composed together, examined and debugged, and that adhere to scikit-learn's Transformer API. Stop writing the same preprocessing boilerplate code again and again!

extra:
  recipe-maintainers:
    - Silun
    - shaypal5
